version: "3.9"

volumes:
  mysql_vol:
  wordpress_vol:

services:
  db:
    image: mysql:5.7
    volumes:
      -   mysql_vol:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppwd
  
  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.2
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppwd
      WORDPRESS_DB_NAME: wordpress